<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InfinityPart.Application\InfinityPart.Application.csproj" />
    <ProjectReference Include="..\InfinityPart.Infrastructure\InfinityPart.Infrastructure.csproj" />
  </ItemGroup>

</Project>
